//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBlibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoffeeOrder
    {
        public string coffeeType { get; set; }
        public string cupSize { get; set; }
        public int coffee_ID { get; set; }
    }
}
